server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: authschema
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: 123



security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: clientid
      clientSecret: clientsecret
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
    resource:
      userInfoUri: http://localhost:8080/user/me
      id: oauth2_application


